// search-form
export const UPDATE_COUNTRY_REQUEST = 'UPDATE_COUNTRY_REQUEST';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_FAIL = 'UPDATE_COUNTRY_FAIL';

// user
export const UPDATE_VK_INFO = 'UPDATE_VK_INFO';
export const UPDATE_GROUPS_REQUEST = 'GET_COMMUNITIES_REQUEST';
export const UPDATE_GROUPS_FAIL = 'GET_COMMUNITIES_FAIL';
export const UPDATE_GROUPS_SUCCESS = 'GET_COMMUNITIES_SUCCESS';
export const MARK_GROUP = 'MARK_GROUP';
export const UPDATE_USER_INFO_REQUEST = 'GET_INFO_REQUEST';
export const UPDATE_USER_INFO_FAIL = 'GET_INFO_FAIL';
export const UPDATE_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const UPDATE_SEARCH_RESULT_USERS_REQUEST = 'UPDATE_SEARCH_RESULT_USERS_REQUEST';
export const UPDATE_SEARCH_RESULT_USERS_FAIL = 'UPDATE_SEARCH_RESULT_USERS_FAIL';
export const UPDATE_SEARCH_RESULT_USERS_SUCCESS = 'UPDATE_SEARCH_RESULT_USERS_SUCCESS';
export const SEARCH_USERS_IN_GROUPS_USERS_START = 'SEARCH_USERS_IN_GROUPS_USERS_START';
export const SEARCH_USERS_IN_GROUPS_USERS_FAIL = 'SEARCH_USERS_IN_GROUPS_USERS_FAIL';
export const SEARCH_USERS_IN_GROUPS_USERS_SUCCESS = 'SEARCH_USERS_IN_GROUPS_USERS_SUCCESS';
export const SEARCH_USERS_IN_GROUPS_USERS_STEP = 'SEARCH_USERS_IN_GROUPS_USERS_STEP';
