// search-form
export const UPDATE_COUNTRY_REQUEST = 'UPDATE_COUNTRY_REQUEST';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const UPDATE_COUNTRY_FAIL = 'UPDATE_COUNTRY_FAIL';

// user
export const UPDATE_VK_INFO = 'UPDATE_VK_INFO';
export const INIT_FIREBASE = 'INIT_FIREBASE';
export const UPDATE_GROUPS_REQUEST = 'GET_COMMUNITIES_REQUEST';
export const UPDATE_GROUPS_FAIL = 'GET_COMMUNITIES_FAIL';
export const UPDATE_GROUPS_SUCCESS = 'GET_COMMUNITIES_SUCCESS';
export const MARK_GROUP = 'MARK_GROUP';
export const UPDATE_USER_INFO_REQUEST = 'GET_INFO_REQUEST';
export const UPDATE_USER_INFO_FAIL = 'GET_INFO_FAIL';
export const UPDATE_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GROUPS_FILTER = 'GROUPS_FILTER';
export const UPDATE_SEARCH_RESULT_USERS_REQUEST = 'UPDATE_SEARCH_RESULT_USERS_REQUEST';
export const UPDATE_SEARCH_RESULT_USERS_FAIL = 'UPDATE_SEARCH_RESULT_USERS_FAIL';
export const UPDATE_SEARCH_RESULT_USERS_SUCCESS = 'UPDATE_SEARCH_RESULT_USERS_SUCCESS';

// search-results
export const SEARCH_USERS_IN_GROUPS_START = 'SEARCH_USERS_IN_GROUPS_START';
export const SEARCH_USERS_IN_GROUPS_FAIL = 'SEARCH_USERS_IN_GROUPS_FAIL';
export const SEARCH_USERS_IN_GROUPS_SUCCESS = 'SEARCH_USERS_IN_GROUPS_SUCCESS';
export const SEARCH_USERS_IN_GROUPS_STEP = 'SEARCH_USERS_IN_GROUPS_STEP';
export const SEARCH_USERS_IN_GROUP_STEP = 'SEARCH_USERS_IN_GROUP_STEP';

// search-objects
export const ADD_OBJECT = 'ADD_OBJECT';
export const MARK_OBJECT = 'MARK_OBJECT';
export const CLEAR = 'CLEAR';

// loading
export const TOGGLE = 'TOGGLE';